import Head from 'next/head'
import Banner from '@/src/components/Banner/Banner'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Card from '@/src/components/Card/Card'
import coffeeStoresData from "../data/coffee-stores.json"
import { FetchCoffeeStores } from '@/lib/coffe-stores'
import useTrackLocation from '@/hooks/useTrackLocation'
import { useEffect, useState } from 'react'


export async function getStaticProps(context) {

  const coffeeStores = await FetchCoffeeStores();

  return {
    props: {
      coffeeStores,
    },
  }
}

/* start of component */
export default function Home({ coffeeStores }) {

    /* aquire user location and return coordinates  */
  const {
    handleTrackLocation, latLong, locationErrorMsg, isFindingLocation
  } = useTrackLocation();

  const [coffeeStoresToRender, setCoffeeStoresToRender] = useState([])



  useEffect( () => {
 /* Aquire a list of sotres and images based on users location */
    async function setCoffeStoresByLocation() {
      if(latLong) {
        try {
          const fetchedCoffeeeStores = await FetchCoffeeStores(latLong, 12);
          console.log({fetchedCoffeeeStores})
          setCoffeeStoresToRender(fetchedCoffeeeStores)
        }
        catch(e) {
          console.log(e)
        }
      }
    }

    setCoffeStoresByLocation();

  }, [latLong])



  function handleOnBannerBtnClick() {
    console.warn("IT WORKS")
    handleTrackLocation();
  }


  return (
    <div className={styles.sectionWrapper}>
      <Head>
        <title>Coffe Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <Banner
          buttonText={
            isFindingLocation ? "Locating..." : "View Stores Nearby"
          }
          handleOnBannerBtnClick={handleOnBannerBtnClick}
        />
        {
        locationErrorMsg ?
        <p>Something went wrong: {locationErrorMsg}</p>
        : null
        }
        <div className={styles.heroImage}>
          <Image
            alt="coffe conoseiur banner"
            src="/images/hero-image.png"
            width={700} height={400}
          />
        </div>

        {coffeeStoresToRender.length > 0
          ?
          <>
            <h2 className={styles.heading2}>Stores Near You</h2>
            <div className={styles.cardLayout}>
              {
                coffeeStoresToRender.map(store => (
                  <Card
                    key={store.id}
                    name={store.name}
                    imgUrl={store.imgUrl}
                    href={`/coffee-store/${store.id}`} />
                ))
              }
            </div>
          </>
          :
          null}

        {coffeeStores.length > 0
          ?
          <>
            <h2 className={styles.heading2}>San Deigo Stores</h2>
            <div className={styles.cardLayout}>
              {
                coffeeStores.map(store => (
                  <Card
                    key={store.id}
                    name={store.name}
                    imgUrl={store.imgUrl}
                    href={`/coffee-store/${store.id}`} />
                ))
              }
            </div>
          </>
          :
          null}

      </main>
    </div>
  )
}