import Head from 'next/head'
import Banner from '@/src/components/Banner/Banner'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Card from '@/src/components/Card/Card'
import coffeeStoresData from "../data/coffee-stores.json"
import { FetchCoffeeStores } from '@/lib/coffe-stores'
import useTrackLocation from '@/hooks/useTrackLocation'


export async function getStaticProps(context) {

  const coffeeStores = await FetchCoffeeStores();

  return {
    props: {
      coffeeStores,
    },
  }
}

/* start of component */
export default function Home({ coffeeStores }) {

  const {handleTrackLocation, latLong, locationErrorMsg, isFindingLocation} = useTrackLocation();

  console.log({latLong, locationErrorMsg})

  function handleOnBannerBtnClick() {
    console.warn("IT WORKS")
    handleTrackLocation();
  }

  return (
    <div className={styles.sectionWrapper}>
      <Head>
        <title>Coffe Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <Banner
          buttonText={
            isFindingLocation ? "Locating..." : "View Stores Nearby"
          }
          handleOnBannerBtnClick={handleOnBannerBtnClick}
        />
        {
        locationErrorMsg ?
        <p>Something went wrong: {locationErrorMsg}</p>
        : null
        }
        <div className={styles.heroImage}>
          <Image
            alt="coffe conoseiur banner"
            src="/images/hero-image.png"
            width={700} height={400}
          />
        </div>
        {coffeeStores.length > 0
          ?
          <>
            <h2 className={styles.heading2}>Toronto stores</h2>
            <div className={styles.cardLayout}>
              {
                coffeeStores.map(store => (
                  <Card
                    key={store.id}
                    name={store.name}
                    imgUrl={store.imgUrl}
                    href={`/coffee-store/${store.id}`} />
                ))
              }
            </div>
          </>
          :
          null}

      </main>
    </div>
  )
}